# kasih worker otomatis menyesuaikan resource vm
worker_processes auto;

# events mengatur bagaimana Nginx menangani koneksi
events {
    # maksimal koneksi yang dapat ditangani oleh setiap worker secara bersamaan
    worker_connections 1024;
}

# config http servernya nginx
http {
    # MIME type identifier
    include       /etc/nginx/mime.types;
    # MIME type default apabila nginx tidak mengetahui tipe file yang diminta, application/octet-stream basically menganggap ini file biasa bukan file khusus
    default_type  application/octet-stream;
    # aktivasi fitur sendfile
    sendfile      on;

    # virtual server setup nginx
    server {
        # port yang dijalankan di 8080, sama dengan Dockerfile
        listen 8080;
        #  server name defaultnya _
        server_name _;

        # ini root directory atau workspacenya server html si nginx, kita harus save website index.html di sini
        root /usr/share/nginx/html;
        # file default yang dibuka ketika client call api GET /
        index index.html;

        location / {
            # jika request client tidak ditemukan, maka set status code 404 not found
            try_files $uri $uri/ =404;
        }
    }
}